---
# Secret
apiVersion: v1
kind: Secret
metadata: 
  name: mysql
type: Opaque
stringData: 
  password: abc12345
---
#Service
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
  ClusterIP: None
---
#StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql
              key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysqldata
          mountPath: /var/lib/mysql
      volumes:
      - name: mysqldata
        persistentVolumeClaim:
          claimName: mysql-db